### ISSUE TITLE
Long processing times cause an "Unauthorized Access" error

### ISSUE THREAD

**Issue by lmirosevic** [fastlane/deliver#470]
It seems when iTC blesses us with 5+ hour processing times, the session expires (a guess?) and our heroic patience is rewarded with a fastlane run fail. 

It would be cool if deliver caught this error if it happens right after iTunes Transporter finishes, and attempts a re-login automatically, and only surfaces the error out on the second attempt.

![screen shot 2015-11-04 at 21 25 41](https://cloud.githubusercontent.com/assets/1628832/10951009/385da916-833b-11e5-9042-9610c546489d.png)

**Comment by ericyahhh** [comment]
Experienced the same problem today.

**Comment by flaushi** [comment]
Jup, me too :/

**Comment by pkclsoft** [comment]
Seeing something similar.  I have an app with 11 languages, and all is fine but after 18 minutes of uploading screenshots, I get:

Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.2/lib/spaceship/client.rb:263:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unauthorized access"]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)

This has happened several times, after roughly the same amount of time.

**Comment by flaushi** [comment]
There was an error in spaceship, which was solved shortly after my post. Try updating spaceship.

And: Try cleaning up your temporary directory (in my case /tmp)

**Comment by pkclsoft** [comment]
Thanks.  My spaceship is I believe the current version.  I've converted my PNG's to JPG files to reduce their size (and therefor, the time taken to upload).  This seems to have made a difference.  On average the PNG's were taking 7 seconds per image (~270 images), and the JPG's are taking about 3.

It would also be great if the tool didn't abort when it finds images for an inactive language.  Just ignore those files and move on.

**Comment by flaushi** [comment]
Another thing you could try is to have two lanes, one only for screenshot submission, and one only for ipa upload.

**Comment by pkclsoft** [comment]
Yes that occurred to me overnight, but it seems that everything has now worked. Thank you for your help.

**Comment by bwang29** [comment]
This is still an issue. Uploading 480 screenshots will fail at 15% in progress.

**Comment by loydbrahn** [comment]
Yeah, I'm currently running into this issue as well. Is there any way to specify individual locales when uploading screenshots? So this can be broken up by locale?

**Comment by RavisMsk** [comment]
Yep, can confirm too. Uploading ~850-900 screenshots, goes unauthorised at about ~120.

**Comment by KrauseFx** [comment]
There is actually a great pull request work in progress that will fix this issue soon :+1: https://github.com/fastlane/spaceship/pull/235
